Data tranformation is necessary to make the data better-organized. Transformed data may be easier for both humans and computers to use. Properly formatted and validated data improves data quality and protects applications from potential landmines such as null values, unexpected duplicates, incorrect indexing, and incompatible formats.

Here, we will be using the New York City Airbnb Open Data to perform data transformation while focusing on following factors:

1. Identify numerical and categorical variables in the dataset
2. Convert date into datetime
3. Transform numerical variables
4. Transform categorical variables

## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import datetime as dt

## Load the data

In [2]:
airbnb_url = 'https://raw.githubusercontent.com/ManarOmar/New-York-Airbnb-2019/master/AB_NYC_2019.csv'

airbnb = pd.read_csv(airbnb_url)

## Data info
Calling info() on our dataset tells us tons of information about our data frame like the shape (rows, columns), the data type of our features, and the memory usage.

In [3]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

## Data Type
Separating our features into numerical and categorical early on is useful and here is a helper function that does that. This is accomplished by using the select_dtypes() function that columns with the ‘object’ data type as categorical and the rest as numerical.

In [4]:
cat_df = airbnb.select_dtypes(include=['object'])
num_df = airbnb.select_dtypes(exclude=['object'])

def printColumnTypes(categorical_df, numeric_df):
    '''separates non-numeric and numeric columns'''
    print("Categorical columns:")
    for col in categorical_df:
        print(col)
    print("")
    print("Numeric columns:")
    for col in numeric_df:
        print(col)

printColumnTypes(cat_df, num_df)

Categorical columns:
name
host_name
neighbourhood_group
neighbourhood
room_type
last_review

Numeric columns:
id
host_id
latitude
longitude
price
minimum_nights
number_of_reviews
reviews_per_month
calculated_host_listings_count
availability_365

Preview the data

In [5]:
airbnb.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

# Convert into DateTime
If you have data that should be a datetime object, but are strings, you can use the pd.to_datetime, and pass it the format that represents your data.
Just like that, the column has converted into a datatime data type.

In [6]:
airbnb['last_review_new'] = pd.to_datetime(airbnb['last_review'], format='%Y-%m-%d')
airbnb['last_review_new'].dtype.type

numpy.datetime64

Now, the new column, 'last_review_new', has the same data as column 'last_review' but in the datetime format. Next, we can apply a series of functions provided by the datetime library, such as extracting year, month, date and weekday.

In [7]:
airbnb['last_review_year'] = airbnb['last_review_new'].dt.year
airbnb['last_review_month'] = airbnb['last_review_new'].dt.month
airbnb['last_review_day'] = airbnb['last_review_new'].dt.day
airbnb['last_review_weekday'] = airbnb['last_review_new'].dt.weekday

In [8]:
airbnb.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,last_review_new,last_review_year,last_review_month,last_review_day,last_review_weekday
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,...,9,2018-10-19,0.21,6,365,2018-10-19,2018.0,10.0,19.0,4.0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,...,45,2019-05-21,0.38,2,355,2019-05-21,2019.0,5.0,21.0,1.0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,...,0,NaN,NaN,1,365,NaT,NaN,NaN,NaN,NaN
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,...,270,2019-07-05,4.64,1,194,2019-07-05,2019.0,7.0,5.0,4.0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,...,9,2018-11-19,0.10,1,0,2018-11-19,2018.0,11.0,19.0,0.0

# Transform Numerical Data
Let's convert the price in USD into EURO and we use a new column 'price_euro' to store the transformed price.

1 usd = 0.87 euro as of 02/06/2022.

In [9]:
airbnb['price_euro'] = airbnb['price']*0.87

In [10]:
airbnb.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,last_review,reviews_per_month,calculated_host_listings_count,availability_365,last_review_new,last_review_year,last_review_month,last_review_day,last_review_weekday,price_euro
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,...,2018-10-19,0.21,6,365,2018-10-19,2018.0,10.0,19.0,4.0,129.63
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,...,2019-05-21,0.38,2,355,2019-05-21,2019.0,5.0,21.0,1.0,195.75
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,...,NaN,NaN,1,365,NaT,NaN,NaN,NaN,NaN,130.50
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,...,2019-07-05,4.64,1,194,2019-07-05,2019.0,7.0,5.0,4.0,77.43
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,...,2018-11-19,0.10,1,0,2018-11-19,2018.0,11.0,19.0,0.0,69.60

# Transform Categorical Variable
Let's convert categorical variable, 'room_type', into numerical.

First, let's look at the unique values in this variable.

In [11]:
airbnb['room_type'].value_counts()

Entire home/apt    25409
Private room       22326
Shared room         1160
Name: room_type, dtype: int64

##Option 1 Find and Replace

let's generate two new variables, private_room and shared_room, and we use entire home/apt as the baseline. Next, we replace the values in the newly generated varaibles accordingly.

In [12]:
airbnb['private_room'] = airbnb['room_type']
airbnb['private_room'].replace(['Entire home/apt', 'Private room','Shared room'],
                             [0,1,0], inplace=True)

In [13]:
airbnb['private_room'].value_counts()

0    26569
1    22326
Name: private_room, dtype: int64

In [14]:
airbnb['shared_room'] = airbnb['room_type']
airbnb['shared_room'].replace(['Entire home/apt', 'Private room','Shared room'],
                             [0,0,1], inplace=True)

In [15]:
airbnb['shared_room'].value_counts()

0    47735
1     1160
Name: shared_room, dtype: int64

In [16]:
airbnb.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,...,calculated_host_listings_count,availability_365,last_review_new,last_review_year,last_review_month,last_review_day,last_review_weekday,price_euro,private_room,shared_room
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,...,6,365,2018-10-19,2018.0,10.0,19.0,4.0,129.63,1,0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,...,2,355,2019-05-21,2019.0,5.0,21.0,1.0,195.75,0,0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,...,1,365,NaT,NaN,NaN,NaN,NaN,130.50,1,0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,...,1,194,2019-07-05,2019.0,7.0,5.0,4.0,77.43,0,0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,...,1,0,2018-11-19,2018.0,11.0,19.0,0.0,69.60,0,0

##Option 2 Get Dummies

We can simply use get_dummies() function to generate a series of dummies for a categorical variable at a time.

In [17]:
airbnb = pd.get_dummies(airbnb, columns=["room_type"])
airbnb.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,price,minimum_nights,...,last_review_year,last_review_month,last_review_day,last_review_weekday,price_euro,private_room,shared_room,room_type_Entire home/apt,room_type_Private room,room_type_Shared room
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,149,1,...,2018.0,10.0,19.0,4.0,129.63,1,0,0,1,0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,225,1,...,2019.0,5.0,21.0,1.0,195.75,0,0,1,0,0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,150,3,...,NaN,NaN,NaN,NaN,130.50,1,0,0,1,0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,89,1,...,2019.0,7.0,5.0,4.0,77.43,0,0,1,0,0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,80,10,...,2018.0,11.0,19.0,0.0,69.60,0,0,1,0,0

In [18]:
airbnb.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,price,minimum_nights,...,last_review_year,last_review_month,last_review_day,last_review_weekday,price_euro,private_room,shared_room,room_type_Entire home/apt,room_type_Private room,room_type_Shared room
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,149,1,...,2018.0,10.0,19.0,4.0,129.63,1,0,0,1,0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,225,1,...,2019.0,5.0,21.0,1.0,195.75,0,0,1,0,0
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,150,3,...,NaN,NaN,NaN,NaN,130.50,1,0,0,1,0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,89,1,...,2019.0,7.0,5.0,4.0,77.43,0,0,1,0,0
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,80,10,...,2018.0,11.0,19.0,0.0,69.60,0,0,1,0,0

References: https://medium.com/bitgrit-data-science-publication/data-cleaning-with-python-f6bc3da64e45